### PR TITLE
see commit message

### PR DESCRIPTION
**Pull request by zyf0330**
@edimuj I know why, because I doesn't pull and merge from your main repository.

### CODE REVIEW

**Comment by edimuj** [comment]
Ok, nice job!

**Comment by edimuj** [comment]
I noticed that the comparison of  bufferSizeInBytes and bufferSize was wrong and fixed that:

From `if (bufferSizeInBytes > bufferSize)` to  `if (bufferSizeInBytes > bufferSize)`

[Reference](https://developer.android.com/reference/android/media/AudioRecord.html#getMinBufferSize(int, int, int))

**Comment by zyf0330** [comment]
@edimuj I don't understand mentioned above, where is the difference between from and to?

**Comment by edimuj** [comment]
Sorry should be:
From if (bufferSizeInBytes > bufferSize) to if (bufferSizeInBytes < bufferSize)

**Comment by zyf0330** [comment]
Are you sure?
This is in constructor [AudioRecord](https://developer.android.com/reference/android/media/AudioRecord.html#AudioRecord(int, int, int, int, int)).bufferSizeInBytes
> See getMinBufferSize(int, int, int) to determine the minimum required buffer size for the successful creation of an AudioRecord instance. Using values smaller than getMinBufferSize() will result in an initialization failure.
So, maybe the buffersize to instance AudioRecord is different from that used to read from recorder into audioBuffer.

**Comment by edimuj** [comment]
Yes, you're right of course. I have some other changes, including iOS native code that I going to push later and will fix this in that commit.

**Comment by zyf0330** [comment]
I just start to program with this plugin on iOS, and hope that you can fix what I meet.
Thanks.

**Comment by edimuj** [comment]
And yes, the bufferSize of the reader is different from the AudioRecord bufferSize. Today we are just using the same user parameter for both, but it would actually be good to for example have a larger AudioRecord buffer than the buffer used to read from it.

For example:
`recorder = new AudioRecord(MediaRecorder.AudioSource.VOICE_RECOGNITION, sampleRateInHz, channelConfig, audioFormat, **bufferSize * 10**);`

while keeping the reading buffer size the same:

`numReadBytes = recorder.read(audioBuffer, 0, bufferSize);`

What do you think?

**Comment by edimuj** [comment]
Sure, I will commit the iOS fixes within the coming hours. I'm testing them on my devices right now.

**Comment by zyf0330** [comment]
I think it should  be ok, at least it doesn't violate principle. 
And I just think of one improvement of bufferSize. That's programmer may concern more about how often buffer data is given. In fact, this interval is `(bufferSize / channels / sampleRate) s`.

**Comment by edimuj** [comment]
I've pushed a change regarding the bufferSize. Now separate sizes are used for writing and reading.

**Comment by zyf0330** [comment]
I put my eye here.

**Pull request merged**
