### PR TITLE
repair problem about setting start boolean param

### PR DESCRIPTION
**Pull request by zyf0330**

### CODE REVIEW

**Comment by zyf0330** [comment]
Why this pull request contains two which has been merged?

**Comment by edimuj** [comment]
Hmm, don't know. It looks like your previous commits (564a56d,  a6ba2b5 and 	8d0d59b) to the log as well as the new one [0fa0024](https://github.com/edimuj/cordova-plugin-audioinput/commit/0fa0024ca92a2892c5a6eb9107bc4509d6661700), so I think it is ok anyway since the new one was the only one that was merged.

**Comment by zyf0330** [comment]
I have a new commit now, and I find if I create a pull request, other history commits will be think about to  merge. It is crazy and confusing.

**Comment by edimuj** [comment]
I agree.

**Pull request merged**
